material_colors = {
    "Air": 'blue',
    "Ground": 'brown',
    "Water": 'cyan',
    "Wood": 'saddlebrown',
    "Carton": 'tan',
    "StrongMetal": 'silver',
    "NormalMetal": 'gray',
    "SoftMetal": 'lightgray',
    "Flesh": 'pink',
    "BloodyFlesh": 'red',
    "Textiles": 'purple',
    "Concrete": 'darkgray',
    "Runway": 'lightblue',
    "Rug": 'magenta',
    "Glass": 'lightblue',
    "Plastic": 'lightgreen',
    "Porcelain": 'white',
    "Rubber": 'black',
    "Fence": 'darkgreen',
    "Gravel": 'lightyellow',
    "Snow": 'white',
    "HumanCollision": 'red',
    "MetalLadder": 'silver',
    "MetalFence": 'silver'
}

# Material mapping
material_mapping = {
    0: "Air",
    1: "Ground",
    2: "Water",
    3: "Wood",
    4: "Carton",
    5: "StrongMetal",
    6: "NormalMetal",
    7: "SoftMetal",
    8: "Flesh",
    9: "BloodyFlesh",
    10: "Textiles",
    11: "Concrete",
    12: "Runway",
    13: "Rug",
    14: "Glass",
    15: "Plastic",
    16: "Porcelain",
    17: "Rubber",
    18: "Fence",
    19: "Gravel",
    20: "Snow",
    21: "HumanCollision",
    22: "MetalLadder",
    23: "MetalFence"
}